/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frame3.java
 *
 * Created on Feb 6, 2015, 10:57:22 PM
 */
package gaknn.gui;

import gaknn.VisualizeData;
import gaknn.datapreprocess.MissingValueFilter;
import gaknn.datapreprocess.OutlierRemoval;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.*;
import java.awt.event.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.*;

/**
 *
 * @author admin
 */
public class Frame3 extends javax.swing.JFrame {

    OutlierRemoval outliers = new OutlierRemoval();
    VisualizeData outs = new VisualizeData();

    /**
     * Creates new form Frame3
     */
    public Frame3() {
        initComponents();
    }
    static final int MY_MINIMUM = 0;
    static final int MY_MAXIMUM = 100;
    String DescriptionLabel;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnSaveM = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        CompleteNote1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        CompleteNote2 = new javax.swing.JLabel();
        BtnSaveRemoved = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        BtnSaveReplaced = new javax.swing.JButton();
        CompleteNote3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jDescription = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preprocess");

        jLabel1.setText("Missing Value Handling & Outlier Handling");

        jButton1.setText("Missing Value Handler");
        jButton1.setToolTipText("Missing Value Handler will remove them from the training dataset.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Missing Value Handling");

        BtnSaveM.setText("Save As...");
        BtnSaveM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveMActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 9));
        jButton5.setText("View Missing Values");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addGap(77, 77, 77)
                .addComponent(CompleteNote1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(BtnSaveM)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnSaveM)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CompleteNote1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButton1)))))
                .addContainerGap())
        );

        jLabel3.setText("Outlier Handling");

        jButton2.setText("Outlier Remover");
        jButton2.setToolTipText("This will remove the outliers in the dataset.");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BtnSaveRemoved.setText("Save As...");
        BtnSaveRemoved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveRemovedActionPerformed(evt);
            }
        });

        jButton4.setText("Outlier Replacer");
        jButton4.setToolTipText("This replaces outliers with an average value for the relavant field");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        BtnSaveReplaced.setText("Save As...");
        BtnSaveReplaced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveReplacedActionPerformed(evt);
            }
        });

        jLabel4.setText("Select outlier detection method:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tukey's Method", "MedCouples"}));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jDescription.setFont(new java.awt.Font("Tahoma", 0, 10));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 9));
        jButton6.setText("View Outliers");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(36, 36, 36)
                                .addComponent(CompleteNote2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(80, 80, 80)
                                .addComponent(CompleteNote3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnSaveReplaced)
                            .addComponent(BtnSaveRemoved))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CompleteNote2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(BtnSaveRemoved))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSaveReplaced)
                    .addComponent(CompleteNote3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(33, 33, 33))
        );

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1)
                .addContainerGap(228, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(492, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String[] args = null;
        MissingValueFilter.main(args);

        //JProgressBar MissingValueProgressBar = new JProgressBar();
//    MissingValueProgressBar.setValue(25);
//    MissingValueProgressBar.setStringPainted(true);
        //  Border border = BorderFactory.createTitledBorder("Reading...");
        //   MissingValueProgressBar.setBorder(border);
//    add(MissingValueProgressBar, BorderLayout.NORTH);
        //String Note1=MissingValueFilter.;
        CompleteNote1.setText("Done!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String[] args = null;
        try {
            // OutlierRemoval.main(args);
            //System.out.println("DescriptionLabel" + DescriptionLabel);
            if (DescriptionLabel.matches("MedCouples")) {
                outliers.outlierRemoverMC();
            } else if (DescriptionLabel.equals("Tukey's Method")) {
                outliers.outlierRemover();
                //outs.outlierRemover();
            }
//            OutlierProgressBar.setValue(25);
//            OutlierProgressBar.setStringPainted(true);
            //  Border border = BorderFactory.createTitledBorder("Reading...");
            //   MissingValueProgressBar.setBorder(border);
//            add(OutlierProgressBar, BorderLayout.NORTH);
        } catch (IOException ex) {
            Logger.getLogger(Frame3.class.getName()).log(Level.SEVERE, null, ex);
        }

        CompleteNote2.setText("Done!!");
}//GEN-LAST:event_jButton2ActionPerformed

    private void BtnSaveMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveMActionPerformed
        JFileChooser saveFile = new JFileChooser();
        File a = new File(GaknnFrame.arffFolderPath + File.separator + "missing_values_filtered.arff");
        saveFile.setSelectedFile(a);
        saveFile.showSaveDialog(null);

        int returnVal = saveFile.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {

            File file = saveFile.getSelectedFile();

            a.renameTo(file);
        }
    }//GEN-LAST:event_BtnSaveMActionPerformed

    private void BtnSaveRemovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveRemovedActionPerformed
        JFileChooser saveFile1 = new JFileChooser();
        File b = new File("Outliers_Removed.arff");
        saveFile1.setSelectedFile(b);
        saveFile1.showSaveDialog(null);

        int returnVal = saveFile1.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {

            File file = saveFile1.getSelectedFile();

            b.renameTo(file);
        }
    }//GEN-LAST:event_BtnSaveRemovedActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            if (DescriptionLabel.matches("MedCouples")) {
                outliers.outlierHandlerMC();
            } else if (DescriptionLabel.equals("Tukey's Method")) {
                outliers.outlierHandler();
            }
            System.out.println(DescriptionLabel);
        } catch (IOException ex) {
            Logger.getLogger(Frame3.class.getName()).log(Level.SEVERE, null, ex);
        }

        CompleteNote3.setText("Done!!!");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BtnSaveReplacedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveReplacedActionPerformed
        JFileChooser saveFile2 = new JFileChooser();
        File b = new File("Outliers_Replaced.arff");
        saveFile2.setSelectedFile(b);
        saveFile2.showSaveDialog(null);

        int returnVal = saveFile2.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {

            File file = saveFile2.getSelectedFile();

            b.renameTo(file);
        }
    }//GEN-LAST:event_BtnSaveReplacedActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        DescriptionLabel = jComboBox1.getSelectedItem().toString();
        if (DescriptionLabel.matches("MedCouples")) {
            jDescription.setText("<html>This is an enhancement to the Tukey's Method for dealing with skewed data. "
                    + "Outlier threshold defines at a distance of 1.5xIQRxe(-3.5MC) from Q1 and Q3 in either side</html>");
        } else if (DescriptionLabel.equals("Tukey's Method")) {
            jDescription.setText("<html>This is the most commonly used outlier detection method. "
                    + "Outlier threshold defines at a distance of 1.5xIQR from Q1 and Q3 in either side </html>");
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Frame8 viewoutlier = new Frame8();
        viewoutlier.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Frame9 missingvals = new Frame9();
        missingvals.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSaveM;
    private javax.swing.JButton BtnSaveRemoved;
    private javax.swing.JButton BtnSaveReplaced;
    private javax.swing.JLabel CompleteNote1;
    private javax.swing.JLabel CompleteNote2;
    private javax.swing.JLabel CompleteNote3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jDescription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
