/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frame7.java
 *
 * Created on Feb 27, 2015, 12:11:44 AM
 */
package gaknn.gui;

import gaknn.OptimizeKNN;
import java.awt.GridLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author admin
 */
public class Frame7 extends javax.swing.JFrame {

    //  static int attributes=OptimizeKNN.fileReaderObject.numatts;
    /**
     * Creates new form Frame7
     */
    public Frame7() {
        initComponents();
        //  System.out.println("numf7: "+attributes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.addTab("Scatter Plot View", jScrollPane1);
        JPanel Panel1 = new JPanel();
        Panel1.setLayout(new GridLayout(2,3));
        //jScrollPane1.setLayout(new JScrollPaneLayout());
        jScrollPane1.add(Panel1);

        for(int i=0;i< GaknnFrame.attribs+1;i++)
        {
            Panel1.add("Image "+i,new JLabel(new ImageIcon(i+".png")));
        }
        jScrollPane1.setViewportView(Panel1);
        jTabbedPane1.addTab("Bar Plot View", jScrollPane2);
        JPanel Panel2 = new JPanel();
        Panel2.setLayout(new GridLayout(2,3));
        //jScrollPane1.setLayout(new JScrollPaneLayout());
        jScrollPane2.add(Panel2);

        for(int i=0;i< GaknnFrame.attribs+1;i++)
        {
            Panel2.add("Image "+i,new JLabel(new ImageIcon("B"+i+".png")));
        }
        jScrollPane2.setViewportView(Panel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame7().setVisible(true);
                // System.out.println("numf7: "+GaknnFrame.attribs);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
